version: "3"
services:
  mongodb:
    image: mongodb/mongodb-community-server:7.0.7-ubi8
    environment:
      - MONGO_INITDB_ROOT_USERNAME=user
      - MONGO_INITDB_ROOT_PASSWORD=pass
    volumes:
      - ./data:/var/lib/mongodb
    ports:
      - "27017:27017"
